stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    params:
      - data_ingestion.test_size
    outs:
    - data/raw


  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw
    - src/data_preprocessing.py
    params:
      - feature_engg.max_features
    outs:
    - data/processed


  feature_engg:
    cmd: python src/feature_engg.py
    deps:
    - data/processed
    - src/feature_engg.py
    outs:
    - data/features

  model_building:
    cmd: python src/model_building.py
    deps:
    - data/features
    - src/model_building.py
    params:
      - model_building.n_estimators
      - model_building.max_depth
    outs:
    - models/random_forest_model.pkl

  model_evaluation:
    cmd: python src\model_evaluation.py
    deps:
    - data/features/test_features.csv
    - models/random_forest_model.pkl
    metrics:
    - metrics_dict.json
